nix/modules/neard/default.nix

fixes https://github.com/kuutamolabs/kuutamod/issues/173

retry downloading genesis if download failed

---

nix/pkgs/db_bench.nix
nix/pkgs/flake-module.nix

Add this as a benchmark for new hardware.

add db_bench from rocksdb

---

src/settings.rs

Use current folder for default of path options

---

nix/modules/kuutamod/default.nix

This secret might be not readable to the kuutamod user.

Install consul token as root

---

nix/pkgs/neard/generic.nix
nix/pkgs/neard/stable.nix
nix/pkgs/neard/unstable.nix

fix Rustc for different version of near

---

tests/kuutamod.py
tests/test_maintenance_shutdown.py
tests/test_multiple_nodes.py

Update block producing test on leader  after failover

---

tests/kuutamod.py
tests/test_maintenance_shutdown.py
tests/test_maintenance_shutdown_metrics.py
tests/test_multiple_nodes.py

add debug test utils for neard

---

tests/log_utils.py
tests/near_network.py
tests/setup_localnet.py
tests/test_maintenance_shutdown.py
tests/test_maintenance_shutdown_metrics.py
tests/test_multiple_nodes.py

add test utils for saving config and logs

---

Justfile

Avoid update unstable to stable version
https://github.com/kuutamolabs/near-staking-knd/pull/369

nix update unstable on rc versions

---

nix/modules/tests/install-nixos.nix
src/bin/kuutamo.rs
src/deploy/install.rs

kuutamo: improve interactive usage

---

nix/modules/kuutamod/default.nix
nix/modules/single-node-validator/consul.nix
nix/modules/tests/install-nixos.nix

This way we can have the key not world-readable.

kuutamod: use LoadCredential to load key

---

.github/workflows/upgrade-flakes.yml
.github/workflows/upgrade-near-cli.yml
.github/workflows/upgrade-neard-config.yml
.github/workflows/upgrade-neard.yml

hi @Mic92, could we let the CI runner 2 hr earlier?  It will be a great time for me to check these out, and respond to it if anything fails.

Modify ci schedule 2 hr earlier

---

nix/modules/toml-mapping.nix
src/deploy/config.rs

Related issue: https://github.com/kuutamolabs/kuutamocore/issues/720

allow ipv4 only

---

.github/workflows/upgrade-neard.yml

fix update rule for neard unstable

---

.github/dependabot.yml

set target-branch of dependabot

---

src/bin/kneard-deploy.rs
src/deploy/rollback.rs
src/deploy/update.rs
src/deploy/utils.rs
tests/test_maintenance_shutdown.py

remove the redundant `Option<>` wrapper on the parameter, and use the default value.

show maintenance shutdown message after completed

---

flake.lock
src/deploy/install.rs
src/deploy/nixos_rebuild.rs

https://github.com/kuutamolabs/near-staking-knd/issues/615

enable crossplatform deployments

---

nix/modules/neard/default.nix

fix https://github.com/kuutamolabs/near-staking-knd/issues/700

kuutamod: retry until genesis file download is complete

---

src/deploy/config.rs

fix token validation message and always install token

---

src/bin/kneard-mgr.rs
src/commands/server.rs

Fix cancel message

---

nix/modules/single-node-validator/default.nix

specify kneard-ctl in active script

---

nix/modules/near-staking-analytics/default.nix

analytics: add support for s3 backup locations
